version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest # Ou 2022-latest
    container_name: omini_sqlserver_dev
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - omini_sqldata:/var/opt/mssql

volumes:
  omini_sqldata: