services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: omini_sqlserver_dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "yourStrong(!)Password"
      HOME: /var/opt/mssql
    ports:
      - "1433:1433"
    volumes:
      - omini_sqldata:/var/opt/mssql

volumes:
  omini_sqldata:
