-- Inserindo dados em Produto (EPIs).
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS PP COM PÓ ', NULL, 'cx', 4, 0, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-04-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS P COM PÓ ', NULL, 'cx', 75, 1, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-05-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS M COM PÓ ', NULL, 'cx', 62, 0, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-06-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS G COM PÓ ', NULL, 'cx', 35, 0, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-07-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('SEM ESTOQUE', '-', 'LUVAS PP SEM PÓ ', NULL, 'cx', 0, 0, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-08-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS P SEM PÓ ', NULL, 'cx', 53, 0, 'ENTRADA', NULL, 'LBM I (R7/R8)', 1, '2024-09-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS M SEM PÓ ', NULL, 'cx', 76, 0, 'ENTRADA', NULL, 'LBM I (R7/R8)', 1, '2024-10-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('SEM ESTOQUE', '-', 'LUVAS G SEM PÓ ', NULL, 'cx', 0, 0, 'ENTRADA', NULL, 'LBM I (R7/R8)', 1, '2024-11-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'MASCARAS CIRURGICAS', NULL, 'cx', 0, 0, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'MASCARAS N95', NULL, 'cx', 0, 0, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'TOUCA ', NULL, 'PCT', 0, 0, 'ENTRADA', NULL, 'Almoxarifado', 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'FACE SHIELD', NULL, NULL, 0, 0, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, quantidadeEstoque, estoqueMinimo, unidadeMedida, dataValidade, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'ÓCULOS DE PROTEÇÃO ', NULL, 'UN', 0, 0, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
