-- Inserindo dados em Produto (EPIs)
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS PP COM PÓ ', NULL, 'cx', '4', NULL, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-04-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS P COM PÓ ', NULL, 'cx', '75', '1', 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-05-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS M COM PÓ ', NULL, 'cx', '62', NULL, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-06-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS G COM PÓ ', NULL, 'cx', '35', NULL, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-07-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('SEM ESTOQUE', '-', 'LUVAS PP SEM PÓ ', NULL, 'cx', '0', NULL, 'ENTRADA', NULL, 'LBM I (R9/R10)', 1, '2024-08-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS P SEM PÓ ', NULL, 'cx', '53', NULL, 'ENTRADA', NULL, 'LBM I (R7/R8)', 1, '2024-09-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'LUVAS M SEM PÓ ', NULL, 'cx', '76', NULL, 'ENTRADA', NULL, 'LBM I (R7/R8)', 1, '2024-10-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('SEM ESTOQUE', '-', 'LUVAS G SEM PÓ ', NULL, 'cx', '1 caixa', NULL, 'ENTRADA', NULL, 'LBM I (R7/R8)', 1, '2024-11-12 00:00:00', NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'MASCARAS CIRURGICAS', NULL, 'cx', NULL, NULL, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'MASCARAS N95', NULL, 'cx', NULL, NULL, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'TOUCA ', NULL, 'PCT', '4 pacotes', NULL, 'ENTRADA', NULL, 'Almoxarifado', 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'FACE SHIELD', NULL, NULL, NULL, NULL, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
INSERT INTO Produto (descricao, codigo, nome, fabricante, quantidadeMedida, quantidadeEstoqueFechado, estoqueMinimo, ocorrencia, dataValidade, localizacao, ativo, dataVerificacao, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '-', 'ÓCULOS DE PROTEÇÃO ', NULL, 'UN', NULL, NULL, 'ENTRADA', NULL, NULL, 0, NULL, NULL, NULL, 9);
