-- Inserindo dados em Produto (Armários).
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 50/P55)','Reagentes Grau HPLC', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 48)','Reagente Metanol', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 49)','Reagentes Triton/ Tween/ DMSO/Formol', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 47)','Reagente Isopropanol', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 46)','Reagentes Acetonitrila e Éter de petróleo', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 44/P45)','Reagentes Fenol e ácidos', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (em cima dos computadores)','Luvas em uso', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 12/P13/p14)','Lixo tóxico', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 21/P22)','Provetas', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 23)','Materiais de proteína', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 24/P25)','Vidrarias em uso', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM III (P 31/P32)','Ponteiras e eppendorf em uso', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM II (A10/A11)','Vidrarias em uso', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM II (A12/A13)','Provetas, Algodão, Gases e Soxhlet', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM II (A3/A4/A5)','Armário controlado pela Polícia Federal', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM II (Embaixo da pia)','Frascos vazios', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM II (Embaixo da pia)','Água sanitária', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM II (A1/A2)','Prateleira 1 Armário controlado pela Polícia Federal ácido sulfúrico (1L)/ ácido clorídrico (2L)  e ácido sulfúrico (2L)', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES (NULL,'Prateleira 2 Não é controlado pela Polícia Federal', NULL, 13);
INSERT INTO Produto (nome, localizacao, fornecedor_id, tipo_produto_id) VALUES ('LBM I (P29 - SALA DO AKTA)','ARMARIO DE CONTROLADOS DA POLICIA FEDERAL ', NULL, 13);