-- Inserindo dados em Produto (Reagentes Líquidos HPLC)
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '1198', 'ALCOOL ISOPROPILICO ', 'ANIDROL', '1L', 'SAIDA', NULL, 2, 0, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '67630', NULL, 'DINAMICA', '1L', 'ENTRADA', NULL, 11, 1, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '5438270250', 'ÁCIDO SULFURICO 98%', 'SIGMA', '250ML', 'ENTRADA', NULL, 3, 1, 'Controlado PF Armário A 3, 4 e 5', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', 'A095527RA', 'ACETONA', 'EXODO', '1L', 'ENTRADA', NULL, 4, 1, 'Controlado PF Armário  A 3, 4 e 5', 0, NULL, ' VOLUME USADO 1,350 ML', NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', 'P.10.0015.000.06.81', NULL, 'DINAMICA', '1L', 'ENTRADA', NULL, 15, 0, 'Controlado PF Armário  A 3, 4 e 5', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE MODERADO', 'R2801091000', 'ACETONITRILA', 'CRQ', '1L', 'ENTRADA', NULL, 0, 1, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '6283', 'ACIDO ACETICO', 'SIGMA ', '1L', 'ENTRADA', NULL, 1, 0, 'Controlado PF Armário  A 3, 4 e 5', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', 'AA08010RA', 'ACIDO ACETICO', 'EXODO', '1L', 'ENTRADA', NULL, 1, 0, 'Controlado PF Armário  A 3, 4 e 5', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '1024441000', 'CLOROFÓRMIO', 'MERCK', '1L', 'ENTRADA', NULL, 1, 0, 'Controlado PF Armário A 3, 4 e 5', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', 'STBK9875', 'DICLOROMETANO', 'MERCK', '1L', 'ENTRADA', NULL, 1, 0, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE MODERADO', '412383', 'METANOL', 'CARLO', '2.5L', 'ENTRADA', NULL, 2, 0, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '34860', 'METHANOL ', 'SIGMA', '2L', 'ENTRADA', NULL, 1, 0, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE CONFORTAVEL', '360457', 'ACETONITRILO', 'SIGMA', '1L', 'ENTRADA', NULL, 1, 0, 'P33 e P34', 0, NULL, NULL, NULL, 4);
INSERT INTO Produto (descricao, codigoInterno, nome, fabricante, numeroLote, unidadeMedida, dataValidade, quantidadeEstoque, estoqueMinimo, localizacao, ativo, dataEntrada, observacoes, fornecedor_id, tipo_produto_id) VALUES ('ESTOQUE MODERADO', '185914', 'Furfural', 'SIGMA', '100 mL', 'ENTRADA', NULL, 0, 1, 'P33 e P34', 0, NULL, NULL, NULL, 4);
